---
- name: Check if site already exists
  stat:
    path: "{{ site_base_path }}/{{ site_name }}"
  register: site_dir_exists

- fail:
    msg: "Site directory already exists"
  when: site_dir_exists.stat.exists

- name: Create content source directory for {{ site_name }}
  file:
    path: "{{ site_base_path }}/{{ site_name }}/html"
    state: directory
    mode: 0755
