---
- hosts: webservers
  become: true
#  become_method: su
#  become_user: apache
  tasks:
  - name: Copy httpd.conf
    copy:
      src: /app/applications/ansiblehelloworld.com/httpConfiguration/httpd/conf/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      #owner: ec2-user
      #group: ec2-user
      mode: 0644
