---
- hosts: webservers
  become: true
  tasks:
  - name: Copy httpd.conf
    copy:
      src: /app/applications/helloworld.com/httpConfiguration/httpd/conf/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
