---
- hosts: webservers
  become: yes
  tasks:
  - name: Create application root Directory
    file: path=/var/www/html/ansiblehelloworld.com/html state=directory
  - name: Copy Web content
    synchronize:
      src: /app/applications/ansiblehelloworld.com/httpContent/html
      dest: /var/www/html/ansiblehelloworld.com
      delete: yes
      recursive: yes
      # File ownership of directory from ansiblehellworld.com needs to be looked at.
