---
- name: Content
  hosts: webservers
  tasks:
  - name: Create html directory for hellworld.com
    file: path=/var/www/html/helloworld.com/html state=directory
  - name: Synchronize hellworld.com html content
    synchronize:
      src: /app/applications/helloworld.com/httpContent/html
      dest: /var/www/html/helloworld.com
      delete: yes
      recursive: yes
