- name: Get web content and configuration from repo files
  hosts: localhost
  roles:
    - repo

- name: Installation
  hosts: webservers
  #hosts: "{{ variable_host | default('webservers') }}"
  serial: "{{ rolling_update_var | default('1') }}"
  roles:
    - web
