---
- name: Configuration
  hosts: webservers
  serial: "{{ rolling_update_var | default('1') }}"
  become: yes
  tasks:
  - name: Synchronize web farm conf directory
    synchronize:
      src: /tmp/git_checkout/webfarmA/config/httpd/conf/
      dest: /etc/httpd/conf/
      delete: yes
      recursive: yes
    notify:
      - restart apache
  - name: Synchronize web farm conf.d directory
    synchronize:
      src: /tmp/git_checkout/webfarmA/config/httpd/conf.d/
      dest: /etc/httpd/conf.d/
      delete: yes
      recursive: yes
    notify:
      - restart apache
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
