---
- name: Content
  hosts: webservers
  serial: "{{ rolling_update_var | default('1') }}"
  tasks:
  - include_tasks: webserver_content_tasks.yml
    with_items:
      - helloworld.com
      - monitoring.com
    loop_control:
      loop_var: site
