---
- name: Create content source directory for {{ site }}
  file: path=/var/www/html/{{ site }}/html state=directory
- name: Synchronize all {{ site }} content
  synchronize:
    src: /tmp/git_checkout/webfarmA/sites/{{ site }}/html
    dest: /var/www/html/{{ site }}
    delete: yes
    recursive: yes
- name: Create {{ site }} logs directory
  file: path=/var/www/html/{{ site }}/logs state=directory
- name: Create {{ site }} configuration directory
  file: path=/var/www/html/{{ site }}/config state=directory
- name: Synchronize {{ site }} configuration, excluding app.ini.
  synchronize:
    src: /tmp/git_checkout/webfarmA/sites/{{ site }}/config
    dest: /var/www/html/{{ site }}
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=app.ini*"
- name: Set config path in prod
  set_fact:
    config_src_path: /tmp/git_checkout/webfarmA/sites/{{ site }}/config/app.ini.prod
  when: ( 'prod' in inventory_file )
- name: Set config path in staging
  set_fact:
    config_src_path: /tmp/git_checkout/webfarmA/sites/{{ site }}/config/app.ini.staging
  when: ( 'staging' in inventory_file )
- name: Set config path in test
  set_fact:
    config_src_path: /tmp/git_checkout/webfarmA/sites/{{ site }}/config/app.ini.test
  when: ( 'test' in inventory_file )
- name: Copy {{ site }} application config file
  copy:
    src: "{{ config_src_path }}"
    dest: /var/www/html/{{ site }}/config/app.ini
    owner: apache
    group: apache
    mode: 0644
