---
- hosts: webservers
  become: yes
  tasks:
  - name: Install Apache
    yum: name=httpd state=present
  - name: Change ownership of html root directory
    file: dest=/var/www/html owner=ec2-user group=ec2-user mode=0777 recurse=yes
  - name: Start Apache
    service: name=httpd state=started
